apiVersion: v1
kind: Service
metadata:
  name:  privateapi
spec:
  selector:
    app:  privateapi
  ports:
  - port:  80
---  
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: privateapi
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: privateapi
    spec:
      containers:
      - name: privateapi
        image: containersdemo.azurecr.io/privateapi:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5