apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: publicapi
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: publicapi
    spec:
      containers:
      - name: publicapi
        image: containersdemo.azurecr.io/publicapi:latest
        ports:
        - containerPort: 80
        env:
        - name: privateapi
          value: privateapi.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5